### ISSUE TITLE
side-channel-protection is too broad a claim

### ISSUE THREAD

**Issue by annevk** [WICG/origin-isolation#20]
Even with https://github.com/annevk/orb successfully deployed there'd still be attacks possible unless you isolate all your resources with `Cross-Origin-Resource-Policy`.

**Comment by domenic** [comment]
So, the specific protection this is attempting to hint at is that if someone embeds you as an iframe, it should be an out-of-process iframe. That is, it is for sites that want to be embedded, but not in a way that allows their contents to be read. (It's not about protecting every resource on your origin.)

Can you think of something clearer to indicate that? `side-channel-protection-when-framed`, perhaps?

**Comment by annevk** [comment]
Maybe agent/document/window-side-channel-protection or some such? Presumably it also applies if you're the top-level and you frame someone else.

**Comment by annevk** [comment]
I also wonder given the set of attacks from XS-Leaks if side-channel is too broad for what this is trying to do, as attacks have used global limits, global caches, querying window[...], manipulating history, etc. as side-channels, all of which would remain viable attack vectors.

How useful are these specific hints especially if a lot of sites start asserting them? Perhaps a single bit is enough?

**Comment by domenic** [comment]
> I also wonder given the set of attacks from XS-Leaks if side-channel is too broad for what this is trying to do, as attacks have used global limits, global caches, querying window[...], manipulating history, etc. as side-channels, all of which would remain viable attack vectors.

In general I am confused by both this and the earlier concern. If you provide a hint saying "I'm trying to protect myself from X", that doesn't mean "I expect to never suffer from attacks of the form X". As such, trying to make "X" super-precise doesn't seem as important to me as you are indicating...

> How useful are these specific hints especially if a lot of sites start asserting them? Perhaps a single bit is enough?

If every site asserts all hints, then it is as useful as a single bit. But otherwise, they are pretty useful. In particular, in Chrome they allow us to choose between various different implementation strategies; see https://github.com/WICG/origin-isolation#implementation-strategies. We'd like to start with the hints, and hope the ecosystem doesn't make them useless.
